src/pipelinesite/manager/urls.py
from django.urls import path

from .views.users import users
from .views.pipelines import pipelines, pipeline_single
from .views.jobs import jobs
from .views.job_single import job_single_view
from .views.tasks import task_list, task_detail_view
from .views.events import event_list, event_detail_view



app_name = 'manager'
urlpatterns = [
    path('users', users, name='users'),

    path('pipelines', pipelines, name='pipeline_list'),
    path('pipelines/<int:pk>', pipeline_single, name='pipeline_single'),

    path('jobs', jobs, name='jobs'),
    path('jobs/<int:pk>', job_single_view, name='job_single_view'),

    path('tasks', task_list, name='tasks'),
    path('tasks/<int:pk>', task_detail_view, name='task_detail_view'),


    path('events', event_list, name='events'),
    path('events/<int:pk>', event_detail_view, name='event_detail_view'),
]

src/pipelinesite/pipelinesite/urls.py
from django.contrib import admin
from django.urls import path, include

from manager.views import home
# from manager.views import pipelines

urlpatterns = [
    path('', home, name='home_page'),
    path('manager/', include('manager.urls'))
    # path('pipelines', pipelines, name='pipelines_page')
]

src/pipelinesite/manager/models.py
from django.db import models

# Create your models here.

src/pipelinesite/manager/views/events.py
from django.core.paginator import Paginator
from django.shortcuts import render

from manager.filters.event_filter import EventFilter
from pipelinesite.models import Events


def event_list(request):

    all_events = Events.objects.all()

    event_filter = EventFilter(request.GET, queryset=all_events)

    paginator = Paginator(event_filter.qs, 20)

    page_number = request.GET.get('page')
    if not page_number:
        page_number = 1

    page_obj = paginator.get_page(page_number)

    end_range = int(page_number) + 4

    if end_range > page_obj.end_index():
        end_range = page_obj.end_index()
    pagination_range = range(int(page_number), end_range)

    context = {'event_page': page_obj,
               'pagination_range': pagination_range,
               'total_pages': paginator.num_pages,
               'event_filter': event_filter,
               }
    return render(request, 'event/event_list_view.html', context)


def event_detail_view(request, pk):
    event = Events.objects.get(pk=pk)

    context = {'event': event}
    return render(request, 'event/event_detail_view.html', context)

src/pipelinesite/manager/views/home.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

# def home(request):
#     return HttpResponse('{% extends "base.html" %}{% load static %}<h1> This is the WINGS PIPELINE Home Page </h1>')

def home(request):
    return render(request, 'home.html')

src/pipelinesite/manager/views/job_single.py
from typing import List

from django.shortcuts import render
from django.urls import reverse
from pipelinesite.models import Jobs, Events

from wpipe.Job import Job as WpipeJob



def job_single_view(request, pk):
    #TODO: Tree view of events and parent events
    # Events page would have jobs that created it and teh job that came from it
    job = Jobs.objects.get(pk=pk)
    # all_jobs = session.query(Job).all()
    # print("ALL THE JOBS:", all_jobs)
    # job = session.query(Job).get(pk) # Sqlalchemy notation

    print('job id and name:', job.id, job)
    # events_tree = events_stack_generator(job.firing_event, 2, 2)
    job_stack = jobs_stack_generator(job, 2, 2)

    print("OUR JOB STACK:", job_stack)

    # sql_alchemy_firing_event = wp.Event.query.filter(id=job.firing_event.id).all()
    # sql_alchemy_firing_event = session.query(Event).get(job.firing_event.id)
    # print("sql alchemy firing event:", sql_alchemy_firing_event)

    context = {'job': job, 'job_stack': job_stack}

    return render(request, 'job/job_single_view.html', context)

# TODO: Add traversing events into this
def events_stack_generator(base_firing_event: Events, parent_count: int, child_count: int) -> dict:
    events_stack = []

    # Process child events
    current_event = base_firing_event
    for i in range(child_count):
        # Check that a child event exists
        # TODO: How do we get the child event?
        # if current_event.
        # current_event =
        events_stack.append({'value': f'test base_event{(child_count-i)*".child"}', 'url': None})

    # Process the base_firing_even

    events_stack.append({'value': f'The base event: ({base_firing_event.id}) {base_firing_event.name}',
                         'url': reverse('manager:event_detail_view', args=[base_firing_event.id])})

    # To properly add these parent jobs to our stack while making traversing easy we need a sub stack that we reverse
    # and extend onto the original stack
    # TODO: Did I hit the end?
    current_event = base_firing_event
    parent_sub_stack = []
    # TODO: Bug on parent firing event
    for i in range(parent_count):
        # Check that there is a parent job and parent job firing_event. Otherwise we break
        if current_event.parent_job is None or current_event.parent_job.firing_event is None:
            print("There were some nones")
            break
        print("Why are we here")
        # Passed out check, assign the current event as the next parent firing event
        current_event = base_firing_event.parent_job.firing_event
        print("parent count: ", i, current_event)

        parent_sub_stack.append({'value': f'Event name: ({current_event.id}) {current_event.name} | {(parent_count-i)*".parent"}',
                                 'url': reverse('manager:event_detail_view', args=[base_firing_event.id])})

    events_stack.extend(parent_sub_stack[::-1])

    print([x['value'] for x in events_stack])
    print([x['value'] for x in events_stack][::-1])

    # TODO: Add some ending indicator if there isn't any parent or children. This can be figured out from the
    return events_stack

# TODO: Get child event for a job.  Then to get it's latest job we would look at the event and use the self.fired_jobs[-1]
#

def jobs_stack_generator(base_job: 'Jobs', parent_count: int, child_count: int) -> List[dict]:

    jobs_stack = []
    print("base_job:", base_job)
    wpipe_base_job = WpipeJob(int(base_job.pk))

    print("THE WPIPE BASE JOB:", wpipe_base_job)
    print("THE WPIPE PARENT JOB:", wpipe_base_job.parent_job)
    print("THE WPIPE PARENT TASK NAME:", wpipe_base_job.task.name)
    print('Wpipe parent jobs:', wpipe_base_job.parent_job)
    print('wpipe child events: ', wpipe_base_job.child_events)
    children = wpipe_base_job.child_events
    print('wpipe child event:', wpipe_base_job.child_event)
    print([child for child in children])

    # Process child jobs
    current_job = base_job
    for i in range(child_count):
        # Check that a child event exists
        # TODO: How do we get the child job?
        # if current_event.
        # current_event =
        jobs_stack.append({'value': f'test base_job{(child_count - i) * ".child"}', 'url': None})

    # Process the base_job

    jobs_stack.append({'value': f'The base job: ({base_job.id}) ',
                         'url': reverse('manager:job_single_view', args=[base_job.id])})

    # To properly add these parent jobs to our stack while making traversing easy we need a sub stack that we reverse
    # and extend onto the original stack
    current_job = wpipe_base_job
    print(f"base job: {current_job.job_id}")
    print(f"parent-base-job: {current_job.parent_job.job_id}")
    print(f"parent-parent-base-job: {current_job.parent_job.parent_job.job_id}")
    parent_sub_stack = []
    for i in range(parent_count):
        # Check that there is a parent job and parent job firing_event. Otherwise we break
        if current_job.firing_event is None or current_job.parent_job is None:
            print("There were some nones")
            break
        # Passed out check, assign the current event as the next parent firing event
        current_job = current_job.parent_job
        print(f'parent count: {parent_count}')
        print(f"current parent job id: {current_job.job_id}")
        parent_sub_stack.append(
            {'value': f'Job name: ({current_job.job_id}) {(parent_count - i) * ".parent"}'})



    jobs_stack.extend(parent_sub_stack[::-1])

    print([x['value'] for x in jobs_stack])
    print([x['value'] for x in jobs_stack][::-1])

    # TODO: Add some ending indicator if there isn't any parent or children. This can be figured out from the
    return jobs_stack

src/pipelinesite/manager/views/jobs.py
import os

import sqlalchemy.orm
from django.db.models import Value, Case, When
from django.shortcuts import render
from django.core.paginator import Paginator
from django.urls import reverse

from pipelinesite.models import Jobs, Events
from pipelinesite.utils import JobStates
from manager.filters.job_filter import JobFilter

# Define sqlalchemy session to be used in methods
# import wpipe as wp
# from wpipe.sqlintf import Session
# from wpipe.sqlintf.Event import Event as SIEvent
from wpipe.sqlintf.Job import Job
from wpipe.Job import Job as WpipeJob
from wpipe.sqlintf.Event import Event

# engine = sqlalchemy.create_engine(os.environ['WPIPE_ENGINEURL'])
# Session = sqlalchemy.orm.sessionmaker(bind=engine)
# session = Session()

def jobs(request):

    # TODO: Add child task.  The current task in job is the parent task.  Code for trying to get the child task
    # Job is object and task is the script that the job runs
    # Event deicdes what task should be assinged to jobs
    # Parent event
    # -> my_job.parent_job.task
    # -> my_event.parent_job.task

    all_jobs = Jobs.objects.\
        annotate(state_integer=Case(
            When(state=JobStates.SUBMITTED.value[0], then=Value(JobStates.SUBMITTED.value[1])),
            When(state=JobStates.INITIALIZED.value[0], then=Value(JobStates.INITIALIZED.value[1])),
            When(state=JobStates.COMPLETED.value[0], then=Value(JobStates.COMPLETED.value[1])),
            When(state=JobStates.KEYBOARD_INTERRUPT.value[0], then=Value(JobStates.KEYBOARD_INTERRUPT.value[1])),
            default=Value(JobStates.ERROR.value[1])
    )).order_by('state_integer', 'starttime')

    jobs_filter = JobFilter(request.GET, queryset=all_jobs)

    paginator = Paginator(jobs_filter.qs, 20)

    page_number = request.GET.get('page')
    if not page_number:
        page_number = 1

    page_obj = paginator.get_page(page_number)

    end_range = int(page_number) + 4

    if end_range > page_obj.end_index():
        end_range = page_obj.end_index()
    pagination_range = range(int(page_number), end_range)

    context = {'jobs_page': page_obj,
               'pagination_range': pagination_range,
               'total_pages': paginator.num_pages,
               'jobs_filter': jobs_filter,
               }

    return render(request, 'job/job_list_view.html', context)

src/pipelinesite/manager/views/pipelines.py
from django.shortcuts import render

from pipelinesite.models import Pipelines, Tasks, Inputs, Targets

def pipelines(request):
    all_pipes = Pipelines.objects.all()
    context = {'pipelines': all_pipes}
    return render(request, 'pipelines.html', context)

def pipeline_single(request, pk):
    # Process request
    pipe = Pipelines.objects.get(pk=pk)
    tasks = Tasks.objects.all().filter(pipeline=pipe)
    pipe_inputs = Inputs.objects.filter(pipeline_id=pipe)
    pipe_config_data_product = pipe.config_data_product
    print('PIPE INPUTS', pipe_inputs)
    all_targets = []
    for input in pipe_inputs:
        print('Input name', input.confpath)
        targets = Targets.objects.filter(input_id=input)
        all_targets.extend(targets)

    for target in all_targets:
        print("    target:", target, target.datapath, target.dataraws)

    # print("PIPELINE", pipe)
    # print("TASKS",  tasks)

    print("    DATAPRODUCTS: ", pipe.config_data_product())
    # see Target.py method configure_target(). self.input.confdataproducts

    context = {'pipeline': pipe, 'tasks': tasks, 'pipe_inputs': pipe_inputs, 'targets': all_targets}
    return render(request, 'pipeline_single.html', context)

src/pipelinesite/manager/views/tasks.py
from django.core.paginator import Paginator
from django.shortcuts import render

from manager.filters.task_filter import TaskFilter
from pipelinesite.models import Tasks


def task_list(request):

    all_tasks = Tasks.objects.all()

    task_filter = TaskFilter(request.GET, queryset=all_tasks)

    paginator = Paginator(task_filter.qs, 20)

    page_number = request.GET.get('page')
    if not page_number:
        page_number = 1

    page_obj = paginator.get_page(page_number)

    end_range = int(page_number) + 4

    if end_range > page_obj.end_index():
        end_range = page_obj.end_index()
    pagination_range = range(int(page_number), end_range)

    context = {'task_page': page_obj,
               'pagination_range': pagination_range,
               'total_pages': paginator.num_pages,
               'task_filter': task_filter,
               }
    return render(request, 'task/task_list_view.html', context)


def task_detail_view(request, pk):
    task = Tasks.objects.get(pk=pk)

    context = {'task': task}
    return render(request, 'task/task_detail_view.html', context)

src/pipelinesite/manager/views/users.py
from django.shortcuts import render

from pipelinesite.models import Users

def users(request):
    all_users = Users.objects.all()
    context = {'users': all_users}
    return render(request, 'users.html', context)

src/pipelinesite/manager/templates/base.html
{% load static %}

<!DOCTYPE html>
<meta charset="UTF-8">

<html>

<head>
<!--  Boostrap core CSS -->

  <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet">
  <script src="{% static 'js/jquery.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
</head>

<div class="container-fluid">
<nav class="navbar navbar-expand-md navbar-dark " style="background-color: #a584f7">
  <a class="navbar-brand" href="#">WINGS</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link" href="{% url 'manager:pipeline_list' %}">Pipelines</a>
      <a class="nav-item nav-link" href="{% url 'manager:users' %}">Users</a>
      <a class="nav-item nav-link" href="{% url 'manager:jobs' %}">Jobs</a>
      <a class="nav-item nav-link" href="{% url 'manager:tasks' %}">Tasks</a>
      <a class="nav-item nav-link" href="{% url 'manager:events' %}">Events</a>
    </div>
  </div>
</nav>



  {% block head %}

  {% endblock %}

</div>


{% block body %}
<!--Pages that extend 'base.html' will override this section-->
{% endblock %}

</html>

{%block script%}
<!--Pages that extend 'base.html' will override this section-->
{% endblock %}

src/pipelinesite/manager/templates/base_min.html
<!-- This is for html files that don't need the full navbar extended -->
{% load static %}

<!DOCTYPE html>
<meta charset="UTF-8">

<html>
<head>
<!--  Boostrap core CSS -->

  <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
  <link href="{% static 'css/bootstrap.css'%}" rel="stylesheet">
  <script src="{% static 'js/jquery.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>

  {% block head %}
  {% endblock %}
</head>

{% block body %}
<!--Pages that extend 'base.html' will override this section-->
{% endblock %}

</html>

{%block script%}
<!--Pages that extend 'base.html' will override this section-->
{% endblock %}

src/pipelinesite/manager/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block body %}


<h1>This is a page</h1>
<title> This is a title</title>
{% endblock %}

{% block script %}
<script>
<!--    $(document).ready(function() {-->
<!--             if (jQuery) {-->
<!--               // jQuery is loaded-->
<!--               alert("Yeah!");-->
<!--             } else {-->
<!--               // jQuery is not loaded-->
<!--               alert("Doesn't Work");-->
<!--             }-->
<!--          });-->
</script>

{% endblock %}

src/pipelinesite/manager/templates/jobs.html
{% extends "base.html" %}
{% block body %}
<head>
    <meta charset="UTF-8">
<!--    {%load static%}-->
<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">-->
    <title>Jobs</title>
</head>

<body>

<div class="container">

    <div class="row">
        <div class="col justify content-center">
            <h2 class="text-center">Jobs </h2>
        </div>
        <hr>
    </div>



    <div class="row">
        <div class="col">
            <table class="table table-striped">
              <tr>
                  <th>ID</th>
                  <th>Attempt</th>
                  <th>State</th>
                  <th>Start Time</th>
                  <th>End Time</th>
                  <th>Node</th>
                  <th>Config</th>
                  <th>Task</th>
                  <th>Firing Event</th>
              </tr>
            {% for job in jobs_page %}
              <tr>
                  <td><a href="{% url 'manager:job_single_view' job.pk %}">{{job.id}}</a></td>
                  <td>{{job.attempt}}</td>
                  <td>{{job.state}}</td>
                  <td>{{job.starttime}}</td>
                  <td>{{job.endtime}}</td>
                  <td>{{job.node}}</td>
                  <td>{{job.config}}</td>
                  <td>{{job.task}}</td>
                  <td>{{job.firing_event}}</td>
              </tr>
            {% endfor %}
            </table>
        </div>

        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
              <li class="page-item">
                  <a class="page-link" href="?page=1">First</a>
              </li>
            {% if jobs_page.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page={{ jobs_page.previous_page_number }}">Previous</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Previous</a>
              </li>
            {% endif %}
            {% for i in pagination_range %}
              {% if jobs_page.number == i %}
                <li class="page-item active" aria-current="page">
                  <span class="page-link">
                    {{ i }}

                  </span>
                </li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if jobs_page.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ jobs_page.next_page_number }}">Next</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1" aria-disabled="True">Next</a>
              </li>
            {% endif %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ total_pages }}">Last</a>
              </li>
          </ul>
        </nav>

<!--        <div class="col">-->
<!--            <div class="pagination">-->
<!--                <span class="step-links">-->
<!--                    {% if jobs_page.has_previous %}-->
<!--                        <a href="?page=1">&laquo; first</a>-->
<!--                        <a href="?page={{ jobs_page.previous_page_number }}">previous</a>-->
<!--                    {% endif %}-->

<!--                    <span class="current">-->
<!--                        Page {{ jobs_page.number }} of {{ jobs_page.paginator.num_pages }}.-->
<!--                    </span>-->

<!--                    {% if jobs_page.has_next %}-->
<!--                        <a href="?page={{ jobs_page.next_page_number }}">next</a>-->
<!--                        <a href="?page={{ jobs_page.paginator.num_pages }}">last &raquo;</a>-->
<!--                    {% endif %}-->
<!--                </span>-->
<!--            </div>-->
<!--        </div>-->

    </div>
</div>

<!--{% for pipe in pipelines %}-->
<!--     <h2>{{pipe.name}} </h2>-->
<!--{% endfor %}-->

</body>
{% endblock %}

src/pipelinesite/manager/templates/pipeline_single.html
{% extends "base.html" %}
{% block body %}
<head>
<!--    <meta charset="UTF-8">-->
<!--    {%load static%}-->
<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">-->
    <title>Pipeline - {{pipeline.name}}</title>
</head>
<body>
<div class="container">

    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-pipe-tab" data-bs-toggle="tab" data-bs-target="#nav-pipe"
                    type="button" role="tab" aria-controls="nav-pipe" aria-selected="true">Pipeline</a>
            <a class="nav-item nav-link" id="nav-targets-tab" data-bs-toggle="tab" data-bs-target="#nav-targets"
                    type="button" role="tab" aria-controls="nav-targets" aria-selected="false">Targets</a>
        </div>
    </nav>

    <div class="tab-content" id="nav-tabContent">

        <div class="tab-pane fade show active" id="nav-pipe" role="tabpanel" aria-labelledby="nav-pipe-tab">
            <div class="row">
                <h1><b>Pipeline</b></h1>
                <hr>
            </div>

            <div class="row">
        <!--        Put a spacer-->

            </div>

            <div class="row">
                <div class="col"l>
                    <h3 class="text-muted">Attributes</h3>
                        <ul>
                            <li><b>ID:</b>  {{ pipeline.pk }} </li>
                            <li><b>Name:</b>   {{ pipeline.name }}</li>
                            <li><b>Description:</b> {% if pipeline.description %} {{  pipeline.description }} {% else %} None {% endif %}</li>
        <!--                    TODO: This needs a better solution -->
                            <li><b>Root Direcotry:</b> {{ pipeline.pipe_root }}
                                <ul>
                                    <li><b>Input root:</b> {{ pipeline.input_root }}</li>
                                    <li><b>Software root:</b> {{ pipeline.software_root }}</li>
                                    <li><b>Data root:</b> {{ pipeline.data_root }}</li>
                                    <li><b>Config root:</b> {{ pipeline.config_root }}</li>
                                </ul>
                            </li>
                            <li><b>Conf Path:</b> {{ pipeline.config_data_product_path }}</li>
                        </ul>
                </div>
            </div>

<!--            <br>-->
<!--            <div class="row">-->
<!--                <div class="col">-->
<!--                    <h3 class="text-muted">Configuration</h3>-->
<!--                    {% for input in pipe_inputs %}-->
<!--                        Conf Path: {{ inputs.confpath }} <br>-->
<!--                    {% endfor %}-->
<!--                </div>-->
<!--            </div>-->

            <br>
            <div class="row">
                <h3 class="text-muted">Tasks</h3>
            </div>

            <div class="row">
                <div class="col">
                    <table class="table table-striped">
                      <tr>
                          <th>pk</th>
                          <th>Name</th>
                          <th>Timestamp</th>
                          <th>N Runs</th>
                          <th>Runtime</th>
                          <th>Is Exclusive</th>
                      </tr>
                    {% for task in tasks %}
                      <tr>
                          <td>{{task.pk}}</td>
                          <td>{{task.name}}</td>
                          <td>{{task.timestamp}}</td>
                          <td>{{task.nruns}}</td>
                          <td>{{task.run_time}}</td>
                          <td>{{task.is_exclusive}}</td>
                      </tr>
                    {% endfor %}
                    </table>
                </div>
            </div>
        </div>

        <div class="tab-pane fade" id="nav-targets" role="tabpanel" aria-labelledby="nav-targets-tab">

        </div>

    </div>

</div>
</body>

<!--Some nonsense code trying to make to make the directories visually make more sense -->
<!--                        <div class="accordion accordion-flush">-->
<!--                            <div class="accordion-item">-->
<!--                                <div class="accordion-header">-->
<!--                                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">-->
<!--                                        <b>Root Direcotry:</b> {{ pipeline.pipe_root }}-->
<!--                                    </button>-->

<!--                                </div>-->
<!--                                <div class="accordion-body">-->
<!--                                    Some other dir that inherits from pipe_root-->
<!--                                </div>-->
<!--                                </div>-->
<!--                            </div>-->

{% endblock %}

src/pipelinesite/manager/templates/pipelines.html
{% extends "base.html" %}
{% block body %}
<head>
    <meta charset="UTF-8">
<!--    {%load static%}-->
<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">-->
<!--    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">-->
    <title>Pipelines</title>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col justify-content-center">
            <h2 class='text-center'>Pipelines</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
           <table class="table table-striped">
              <tr>
                  <th>Id</th>
                  <th>Name</th>
                  <th>Pipeline Root</th>
                  <th>description</th>
                  <th>User</th>
              </tr>
            {% for pipe in pipelines %}
              <tr>
                  <td><a href="{% url 'manager:pipeline_single' pipe.pk %}">{{pipe.id}}</a></td>
                  <td>{{pipe.name}}</td>
                  <td>{{pipe.pipe_root}}</td>
                  <td>{{pipe.description}}</td>
                  <td>{{pipe.user.name}}</td>
              </tr>
            {% endfor %}
            </table>
        </div>


    </div>
</div>

<!--{% for pipe in pipelines %}-->
<!--     <h2>{{pipe.name}} </h2>-->
<!--{% endfor %}-->

</body>
{% endblock %}

src/pipelinesite/manager/templates/users.html
{% extends "base.html" %}

{% block body %}
<head>
<!--    <meta charset="UTF-8">-->
<!--&lt;!&ndash;    {%load static%}&ndash;&gt;-->
<!--&lt;!&ndash;    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">&ndash;&gt;-->
<!--&lt;!&ndash;    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">&ndash;&gt;-->
    <title>Users</title>
</head>
<body>

<table class="table table-striped">
  <tr>
      <th>Name</th>
      <th>Timestamp</th>
  </tr>
{% for user in users %}
  <tr>
      <th>{{user.name}}</th>
      <th>{{user.timestamp}}</th>
  </tr>
{% endfor %}
</table>

<!--{% for pipe in pipelines %}-->
<!--     <h2>{{pipe.name}} </h2>-->
<!--{% endfor %}-->

{% endblock %}